/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e0e3e5',
        'on-surface-variant': '#464555',
        'on-tertiary-fixed-variant': '#7b2f00',
        'on-secondary-fixed': '#140f54',
        'secondary-container': '#b6b4ff',
        'on-tertiary-container': '#ffd2be',
        'on-secondary-container': '#454386',
        'primary-fixed-dim': '#c3c0ff',
        'surface-tint': '#4d44e3',
        'on-primary-fixed-variant': '#3323cc',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdbcc',
        'on-primary-fixed': '#0f0069',
        'primary-container': '#4f46e5',
        'inverse-on-surface': '#eff1f3',
        'surface-container': '#eceef0',
        'outline-variant': '#c7c4d8',
        'secondary-fixed-dim': '#c3c0ff',
        'secondary-fixed': '#e2dfff',
        'surface-container-high': '#e6e8ea',
        'surface-dim': '#d8dadc',
        'primary-fixed': '#e2dfff',
        'on-secondary-fixed-variant': '#413f82',
        'on-secondary': '#ffffff',
        'on-surface': '#191c1e',
        'inverse-surface': '#2d3133',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'on-background': '#191c1e',
        'tertiary-fixed-dim': '#ffb695',
        'primary': '#3525cd',
        'surface-container-low': '#f2f4f6',
        'on-primary-container': '#dad7ff',
        'tertiary-container': '#a44100',
        'background': '#f7f9fb',
        'tertiary': '#7e3000',
        'error-container': '#ffdad6',
        'secondary': '#58579b',
        'on-error': '#ffffff',
        'surface': '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#351000',
        'surface-variant': '#e0e3e5',
        'inverse-primary': '#c3c0ff',
        'surface-container-lowest': '#ffffff',
        'outline': '#777587',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms')
  ],
}
